### PR TITLE
Slovak language

### PR DESCRIPTION
**Pull request by grafitek**
Hi,
I translated PerfexCRM into the Slovak language.
Translated files sent here:
[slovak.zip](https://github.com/mstojanovv/PerfexCRM/files/2567747/slovak.zip)

### CODE REVIEW

**Comment by mstojanovv** [comment]
Hello.

There are some conflicts with the German language, can you please re-check them?
I can also manually push the Slovak language so you can pull it on your side.

Regards.

**Comment by grafitek** [comment]
Hello,
I'm sending a modified Slovak language :-)

[slovak.zip](https://github.com/mstojanovv/PerfexCRM/files/2577981/slovak.zip)

**Comment by mstojanovv** [comment]
Thanks, i copied the files and will push them manually because there is a conflict.

**Comment by grafitek** [comment]
Thank ;)

**Pull request closed without merging**
